import React from "react";
import "./load-view.sass"

export const LoadView = () =>
{
    return (
        <div className="loadingio-spinner-eclipse-j6bz9624dx">
            <div className="ldio-0qmq0nafzgsp">
                <div></div>
            </div>
        </div>
        /* generated by https://loading.io/ */
    );
}